version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: kitashiru
      POSTGRES_PASSWORD: kitashirupw
      POSTGRES_DB: kitashiruAPI
    restart: always
    networks:
      - lesson
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=dev
      - POSTGRES_USER=kitashiru
      - POSTGRES_PW=kitashirupw
      - POSTGRES_HOST=dev-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kitashiruAPI
    depends_on:
      - dev-postgres
    networks:
      - lesson
    volumes:
      - .:/app
networks:
  lesson: