# Dockerfile.migrate
FROM golang:1.18-alpine

# Install bash, curl, and migrate
RUN apk add --no-cache bash curl && \
    curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar -xvzf - && \
    mv migrate /usr/local/bin/migrate

# Set the working directory
WORKDIR /app
